const AccountConstant = {
	SET_DATA: '[ACCOUNT] SET_DATA',
	GET_ACCOUNT_SUCCESS: '[ACCOUNT] GET_ACCOUNT_SUCCESS',
	DELETE_ACCOUNT_SUCCESS: '[ACCOUNT] DELETE_ACCOUNT_SUCCESS',
	GET_STAFF_SUCCESS: '[ACCOUNT] GET_STAFF_SUCCESS',
	DELETE_PRODUCT_SUCCESS: '[ACCOUNT] DELETE_PRODUCT_SUCCESS'
}

export default AccountConstant 
