const MangeProductConstant = {
	SET_DATA: '[MANAGE_PRODUCT] SET_DATA',
	GET_CATEGORY_SUCCESS: '[MANAGE_PRODUCT] GET_CATEGORY_SUCCESS',
	DELETE_CATEGORY_SUCCESS: '[MANAGE_PRODUCT] DELETE_CATEGORY_SUCCESS',
	GET_PRODUCT_SUCCESS: '[MANAGE_PRODUCT] GET_PRODUCT_SUCCESS',
	DELETE_PRODUCT_SUCCESS: '[MANAGE_PRODUCT] DELETE_PRODUCT_SUCCESS'
}

export default MangeProductConstant 
