const MangeProductConstant = {
	SET_DATA: '[MANAGE_PRODUCT] SET_DATA',
	GET_CATEGORY_SUCCESS: '[MANAGE_PRODUCT] GET_CATEGORY_SUCCESS',
	DELETE_CATEGORY_SUCCESS: '[MANAGE_PRODUCT] DELETE_CATEGORY_SUCCESS'
}

export default MangeProductConstant 
