const CartConstant = {
	GET_LIST_CART_ITEM_SUCCESS: '[CART] GET_LIST_CART_ITEM_SUCCESS',
	UPDATE_QUANTITY_CART_SUCCESS: '[CART] UPDATE_QUANTITY_CART_SUCCESS',
	REMOVE_CART_ITEM_SUCCESS: '[CART] REMOVE_CART_ITEM_SUCCESS'
}

export default CartConstant
