const CartConstant = {
	GET_LIST_CART_ITEM_SUCCESS: '[CART] GET_LIST_CART_ITEM_SUCCESS',
	UPDATE_QUANTITY_CART_SUCCESS: '[CART] UPDATE_QUANTITY_CART_SUCCESS',
	REMOVE_CART_ITEM_SUCCESS: '[CART] REMOVE_CART_ITEM_SUCCESS',
	SET_COUNT_CART_ITEM: '[CART] SET_COUNT_CART_ITEM',
	UPDATE_COUNT_CART_ITEM: '[CART] UPDATE_COUNT_CART_ITEM',
	SET_INFO_CHECKOUT: '[CART] SET_INFO_CHECKOUT'
}

export default CartConstant
