const DashboardConstant = {
	SET_TYPE_CONTENT_COMPONENT: '[USER_DASHBOARD] SET_TYPE_CONTENT_COMPONENT',
	TYPE_CONTENT_COMPONENT: {
		USER: 'user',
		ORDER: 'order',
		CHANGE_PASSWORD: 'change_password',
		ADDRESS: 'address'
	},
	GET_LIST_ADDRESS_SUCCESS: '[USER_DASHBOARD] GET_LIST_ADDRESS_SUCCESS',
	GET_USER: '[USER_DASHBOARD] GET_USER',
	GET_INFO_USER_SUCCESS: '[USER_DASHBOARD] GET_INFO_USER_SUCCESS',
	UPDATE_USER_SUCCESS: '[USER_DASHBOARD] UPDATE_USER_SUCCESS',
	SET_IS_EDIT: '[USER_DASHBOARD] SET_IS_EDIT',
	IMG_USER_DEFAULT: 'https://w7.pngwing.com/pngs/842/992/png-transparent-discord-computer-servers-teamspeak-discord-icon-video-game-smiley-online-chat-thumbnail.png',
	SET_TYPE_UI_ADDRESS: '[USER_DASHBOARD] SET_TYPE_UI_ADDRESS',
	SET_ADD_ADDRESS_SUCCESS: '[USER_DASHBOARD] SET_ADD_ADDRESS_SUCCESS',
	SET_REMOVE_ADDRESS_SUCCESS: '[USER_DASHBOARD] SET_REMOVE_ADDRESS_SUCCESS',
	SET_UPDATE_ADDRESS_SUCCESS: '[USER_DASHBOARD] SET_UPDATE_ADDRESS_SUCCESS', 
	GET_LIST_ORDER_SUCCESS: '[USER_DASHBOARD] GET_LIST_ORDER_SUCCESS',
	GET_LIST_ORDER_ITEM_SUCCESS: '[USER_DASHBOARD] GET_LIST_ORDER_ITEM_SUCCESS'
}

export default DashboardConstant
