const DashboardConstant = {
	SET_TYPE_CONTENT_COMPONENT: '[USER_DASHBOARD] SET_TYPE_CONTENT_COMPONENT',
	TYPE_CONTENT_COMPONENT: {
		USER: 'user',
		ORDER: 'order',
		CHANGE_PASSWORD: 'change_password',
		ADDRESS: 'address'
	},
	GET_LIST_ADDRESS_SUCCESS: '[USER_DASHBOARD] GET_LIST_ADDRESS_SUCCESS',
	GET_USER: '[USER_DASHBOARD] GET_USER',
	GET_INFO_USER_SUCCESS: '[USER_DASHBOARD] GET_INFO_USER_SUCCESS'
}

export default DashboardConstant
