const DashboardConstant = {
	SET_TYPE_CONTENT_COMPONENT: '[USER_DASHBOARD] SET_TYPE_CONTENT_COMPONENT',
	TYPE_CONTENT_COMPONENT: {
		USER: 'user',
		ORDER: 'order',
		CHANGE_PASSWORD: 'change_password',
		ADDRESS: 'address',
		MESSAGE: 'message'
	},
	GET_LIST_ADDRESS_SUCCESS: '[USER_DASHBOARD] GET_LIST_ADDRESS_SUCCESS',
	GET_USER: '[USER_DASHBOARD] GET_USER',
	GET_INFO_USER_SUCCESS: '[USER_DASHBOARD] GET_INFO_USER_SUCCESS',
	UPDATE_USER_SUCCESS: '[USER_DASHBOARD] UPDATE_USER_SUCCESS',
	SET_IS_EDIT: '[USER_DASHBOARD] SET_IS_EDIT',
	IMG_USER_DEFAULT: 'https://drive.google.com/thumbnail?id=1EqHfQ_wmzFL9NUtwQY8E3Ll9QvHidDmq',
	IMG_STORE_DEFAULT: 'https://drive.google.com/thumbnail?id=1TFmW0AF4gLO8Pq322nrMdgQ8d-sE2EDM',
	SET_TYPE_UI_ADDRESS: '[USER_DASHBOARD] SET_TYPE_UI_ADDRESS',
	SET_ADD_ADDRESS_SUCCESS: '[USER_DASHBOARD] SET_ADD_ADDRESS_SUCCESS',
	SET_REMOVE_ADDRESS_SUCCESS: '[USER_DASHBOARD] SET_REMOVE_ADDRESS_SUCCESS',
	SET_UPDATE_ADDRESS_SUCCESS: '[USER_DASHBOARD] SET_UPDATE_ADDRESS_SUCCESS', 
	GET_LIST_ORDER_SUCCESS: '[USER_DASHBOARD] GET_LIST_ORDER_SUCCESS',
	GET_LIST_ORDER_ITEM_SUCCESS: '[USER_DASHBOARD] GET_LIST_ORDER_ITEM_SUCCESS',
	GET_ORDER_SUCCESS: '[USER_DASHBOARD] GET_ORDER_SUCCESS'
}

export default DashboardConstant
