const HomeConstant = {
	SET_IS_OPEN_CART_CHECKOUT: '[HOME] SET_IS_OPEN_CART_CHECKOUT',
	SET_IS_OPEN_FOOD_DETAIL: '[HOME] SET_IS_OPEN_FOOD_DETAIL',
	GET_LIST_CATEGORY_SUCCESS: '[HOME] GET_LIST_CATEGORY_SUCCESS',
	GET_LIST_PRODUCT_SUCCESS: '[HOME] GET_LIST_PRODUCT_SUCCESS'
}

export default HomeConstant
